### ISSUE TITLE
Trigger multiple backends for same tag

### ISSUE THREAD

**Issue by syphernl** [felskrone/salt-eventsd#38]
Is it possible to use multiple backends for the same tag? For instance two backends that react to the `state.highstate`. One to insert data into a database and the other to send a message to Slack.

They could be combined into one backend, but that makes it less practical.

Should I simply configure it like:
```
events:
   inserter:
      backend: Insert_Worker
      tag: salt/job/[0-9]*/new
   notify:
      backend: Notify_Worker
      tag: salt/job/[0-9]*/new
```

or would this only trigger one of the two?
